# Generated by Django 5.2.15 on 2026-07-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['name'], 'verbose_name': 'Camera', 'verbose_name_plural': 'Cameras'},
        ),
        migrations.RemoveField(
            model_name='camera',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='camera',
            name='lan_ip',
            field=models.GenericIPAddressField(blank=True, help_text='LAN IPv4 address of the camera.', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_password',
            field=models.CharField(blank=True, help_text='RTSP password (to be encrypted in a future version).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_path',
            field=models.CharField(blank=True, help_text="RTSP stream path, beginning with '/'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_port',
            field=models.PositiveIntegerField(default=554, help_text='RTSP port exposed by the camera.'),
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_username',
            field=models.CharField(blank=True, help_text="Username used to authenticate to the camera's RTSP server.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='viewer_url',
            field=models.URLField(blank=True, help_text='Public URL that users access to view the stream (typically the go2rtc WebRTC viewer).', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether this camera should be available to users.'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(help_text='Friendly name displayed throughout the application.', max_length=100, unique=True),
        ),
    ]
