# Generated by Django 5.2.15 on 2026-07-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_options_remove_camera_stream_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='lan_ip',
            field=models.GenericIPAddressField(help_text='LAN IPv4 address of the camera.', protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_password',
            field=models.CharField(help_text='RTSP password (to be encrypted in a future version).', max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_path',
            field=models.CharField(help_text="RTSP stream path, beginning with '/'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_username',
            field=models.CharField(help_text="Username used to authenticate to the camera's RTSP server.", max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='viewer_url',
            field=models.URLField(help_text='Public URL that users access to view the stream (typically the go2rtc WebRTC viewer).'),
        ),
    ]
