# Generated by Django 5.2.15 on 2026-07-11 16:37

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_camera_lan_ip_alter_camera_rtsp_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_password',
            field=encrypted_fields.fields.EncryptedTextField(help_text='RTSP password (to be encrypted in a future version).', max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_username',
            field=encrypted_fields.fields.EncryptedTextField(help_text="Username used to authenticate to the camera's RTSP server.", max_length=100),
        ),
    ]
