# Generated by Django 5.2.15 on 2026-07-11 16:52

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_alter_camera_rtsp_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_password',
            field=encrypted_fields.fields.EncryptedTextField(help_text='RTSP password (to be encrypted in a future version).'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_username',
            field=encrypted_fields.fields.EncryptedTextField(help_text="Username used to authenticate to the camera's RTSP server."),
        ),
    ]
